//  Pipeline code for my New repo of index.html file and hosted it on apache2 server with git polling 
// so if any changes reflefts then it automaticaaly update the server

    pipeline {
    agent any

    stages {
        stage('Deploy') {
            steps {
                git branch: 'main', changelog: false, url: 'https://github.com/jaysisharma/New.git'
                sh 'cp * /var/www/html'
                echo "Deploy Successful"
            }
        }
    }
}
